package cz.addai.components;

import com.ibm.watson.assistant.v2.model.MessageContext;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

import java.io.Serializable;

@Component
@Scope(value = WebApplicationContext.SCOPE_SESSION, proxyMode = ScopedProxyMode.TARGET_CLASS)
public class UserSession implements Serializable {

    // Once the session is crated (opened)
    private String watsonSessionToken;

    // Watson message context - may be null
    private MessageContext watsonMessageContext;

    // Unique request ID generated by device
    private String requestId;

    // ID of required client
    private String clientId;

    public String getWatsonSessionToken() {
        return watsonSessionToken;
    }

    public void setWatsonSessionToken(String watsonSessionToken) {
        this.watsonSessionToken = watsonSessionToken;
    }

    public boolean hasSession() {
        return watsonSessionToken != null;
    }

    public void deleteSession() {
        watsonSessionToken = null;
    }

    public MessageContext getWatsonMessageContext() {
        return watsonMessageContext;
    }

    public void setWatsonMessageContext(MessageContext messageContext) {
        this.watsonMessageContext = messageContext;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }
}
