package cz.addai.components.session;

import cz.addai.persistence.domain.Client;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

import java.io.Serializable;

@Component
@Scope(value = WebApplicationContext.SCOPE_SESSION, proxyMode = ScopedProxyMode.TARGET_CLASS)
public class UserSession implements Serializable {

    // Watson data - may be null
    private WatsonData watsonData;

    // Unique request ID generated by device
    private String requestId;

    // ID of required client
    private String clientId;

    // Required client
    private Client client;

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public WatsonData getWatsonData() {
        return watsonData;
    }

    public void setWatsonData(WatsonData watsonData) {
        this.watsonData = watsonData;
    }

    public void deleteWatsonData() {
        this.watsonData = null;
    }
}
